// Code generated by "stringer -type=Type -trimprefix=Type,type -linecomment"; DO NOT EDIT.

package media

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUndefined-0]
	_ = x[TypeStoryPhoto-1]
	_ = x[typeSentinel-2]
}

const _Type_name = "undefinedstory_photosentinel"

var _Type_index = [...]uint8{0, 9, 20, 28}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
