release:
  github:
    owner: obalunenko
    name: instadiff-cli

before:
  hooks:
    - echo "no hooks yet"

builds:
  - id: cli
    binary: instadiff-cli
    goos:
     - darwin
     - windows
     - linux
    goarch:
     - amd64
     - arm
    env:
     - CGO_ENABLED=0
    main: ./cmd/instadiff-cli
    ldflags:
     - -s -w
     - -X main.version={{.Version}}
     - -X main.commit={{.ShortCommit}}
     - -X main.date={{.Date}}
     - -X main.goversion={{.Env.GOVERSION}}

archives:
  - id: cli
    builds:
      - cli
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - docker-compose.yml
      - config-example.json

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - "^readme"
      - "^scripts"
      - "scripts:"
      - Merge pull request
      - Merge branch
      - Rebase on master
      - "^Makefile"
      - "goreleaser"
