// Code generated by "stringer -type=UsersBatchType -trimprefix=UsersBatchType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UsersBatchTypeUnknown-0]
	_ = x[UsersBatchTypeFollowers-1]
	_ = x[UsersBatchTypeFollowings-2]
	_ = x[UsersBatchTypeNotMutual-3]
	_ = x[UsersBatchTypeBusinessAccounts-4]
	_ = x[usersBatchTypeSentinel-5]
}

const _UsersBatchType_name = "UnknownFollowersFollowingsNotMutualBusinessAccountsusersBatchTypeSentinel"

var _UsersBatchType_index = [...]uint8{0, 7, 16, 26, 35, 51, 73}

func (i UsersBatchType) String() string {
	if i < 0 || i >= UsersBatchType(len(_UsersBatchType_index)-1) {
		return "UsersBatchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UsersBatchType_name[_UsersBatchType_index[i]:_UsersBatchType_index[i+1]]
}
