// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package bar

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[typeUnknown-0]
	_ = x[TypeRendered-1]
	_ = x[TypeVoid-2]
	_ = x[typeSentinel-3]
}

const _Type_name = "typeUnknownRenderedVoidtypeSentinel"

var _Type_index = [...]uint8{0, 11, 19, 23, 35}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
