// Code generated by "stringer -type=userAction -trimprefix=userAction"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[userActionUnknown-0]
	_ = x[userActionFollow-1]
	_ = x[userActionUnfollow-2]
	_ = x[userActionBlock-3]
	_ = x[userActionUnblock-4]
	_ = x[userActionSentinel-5]
}

const _userAction_name = "UnknownFollowUnfollowBlockUnblockSentinel"

var _userAction_index = [...]uint8{0, 7, 13, 21, 26, 33, 41}

func (i userAction) String() string {
	if i >= userAction(len(_userAction_index)-1) {
		return "userAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _userAction_name[_userAction_index[i]:_userAction_index[i+1]]
}
